import type { Skill } from '../memory/skillStore';

export const BUILTIN_SKILLS: Skill[] = [
  {
    id: 'builtin:explain-code',
    name: 'Explain Code',
    tags: ['explain', 'understand'],
    description: 'Step-by-step explanation of code logic',
    content: 'When asked to explain code: describe what it does in plain English, identify the algorithm or pattern used, note any edge cases or gotchas, and suggest improvements if obvious.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:write-tests',
    name: 'Write Tests',
    tags: ['test', 'jest', 'vitest', 'unit'],
    description: 'Generate unit tests for a function or module',
    content: 'When writing tests: use the existing test framework in the project. Cover happy path, edge cases, and error cases. Mock external dependencies. Name tests descriptively using \'should...\' pattern.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:fix-bug',
    name: 'Fix Bug',
    tags: ['fix', 'debug', 'error', 'bug'],
    description: 'Diagnose and fix a bug in code',
    content: 'When fixing bugs: first read the file, identify the root cause, explain what was wrong, make the minimal surgical fix using edit_file, then verify with get_diagnostics.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:code-review',
    name: 'Code Review',
    tags: ['review', 'quality', 'best-practices'],
    description: 'Review code for quality, bugs, and improvements',
    content: 'When reviewing code: check for correctness, edge cases, performance issues, security concerns, readability. Give structured feedback: critical issues first, then suggestions.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:add-types',
    name: 'Add TypeScript Types',
    tags: ['types', 'typescript', 'ts'],
    description: 'Add or improve TypeScript type annotations',
    content: 'When adding types: infer from usage context, prefer specific types over \'any\', use generics where appropriate, add return types to all functions.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:git-summary',
    name: 'Git Summary',
    tags: ['git', 'summary', 'commit', 'log'],
    description: 'Summarize git status and recent changes',
    content: 'When summarizing git state: run git_status, git_log (last 10), git_diff. Present modified files grouped by type, summarize what changed and why based on commit messages.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:optimize-code',
    name: 'Optimize Code',
    tags: ['optimize', 'performance', 'refactor'],
    description: 'Improve code performance and readability',
    content: 'When optimizing: identify bottlenecks first (don\'t premature optimize), suggest algorithmic improvements, reduce unnecessary allocations, simplify complex logic.',
    createdAt: 0,
    useCount: 0,
  },
  {
    id: 'builtin:add-docs',
    name: 'Add Documentation',
    tags: ['docs', 'jsdoc', 'comments'],
    description: 'Add JSDoc/TSDoc comments to functions and classes',
    content: 'When adding docs: write JSDoc for every exported function/class/type. Include @param, @returns, @throws. Keep descriptions concise and accurate to the actual implementation.',
    createdAt: 0,
    useCount: 0,
  },
];
